name: 👷Flow

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  merge_group:


jobs:
  lint:
    uses: mraniki/coding_toolset/.github/workflows/🦺Lint.yml@main
    secrets: inherit
  deploy:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/🧪Test.yml@main
    secrets: inherit